# Generated by Django 4.0.6 on 2022-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.TextField()),
                ('scientific_name', models.TextField()),
                ('rarity', models.PositiveSmallIntegerField()),
                ('location', models.TextField()),
                ('NOAA_fisheries_region', models.TextField()),
                ('color', models.TextField()),
                ('population', models.TextField()),
                ('species_illustration_photo', models.TextField()),
                ('Physical_Description', models.TextField()),
                ('biology', models.TextField()),
                ('taste', models.TextField()),
                ('texture', models.TextField()),
                ('image_gallery', models.TextField()),
            ],
        ),
    ]
