# Generated by Django 4.0.6 on 2022-07-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_backend', '0002_remove_fish_image_gallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='NOAA_fisheries_region',
            new_name='noaa_fisheries_region',
        ),
    ]
