# Generated by Django 4.0.6 on 2022-07-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_backend', '0003_rename_noaa_fisheries_region_fish_noaa_fisheries_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='Physical_Description',
            new_name='physical_description',
        ),
    ]
