# Generated by Django 4.0.6 on 2022-07-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_backend', '0004_rename_physical_description_fish_physical_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='color',
        ),
    ]
