# Generated by Django 4.0.6 on 2022-07-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_backend', '0005_remove_fish_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='image_gallery',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='species_illustration_photo',
            field=models.TextField(null=True),
        ),
    ]
