# Generated by Django 4.0.6 on 2022-07-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_backend', '0007_alter_fish_biology_alter_fish_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image_gallery',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='species_illustration_photo',
            field=models.JSONField(null=True),
        ),
    ]
