# Generated by Django 4.0.6 on 2022-07-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_backend', '0008_alter_fish_image_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
